// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_shared_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_shared_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_shared_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_shared_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shared_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace tibia {
namespace protobuf {
namespace shared {

enum PLAYER_ACTION : int {
  PLAYER_ACTION_NONE = 0,
  PLAYER_ACTION_LOOK = 1,
  PLAYER_ACTION_USE = 2,
  PLAYER_ACTION_OPEN = 3,
  PLAYER_ACTION_AUTOWALK_HIGHLIGHT = 4
};
bool PLAYER_ACTION_IsValid(int value);
constexpr PLAYER_ACTION PLAYER_ACTION_MIN = PLAYER_ACTION_NONE;
constexpr PLAYER_ACTION PLAYER_ACTION_MAX = PLAYER_ACTION_AUTOWALK_HIGHLIGHT;
constexpr int PLAYER_ACTION_ARRAYSIZE = PLAYER_ACTION_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PLAYER_ACTION_descriptor();
template<typename T>
inline const std::string& PLAYER_ACTION_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PLAYER_ACTION>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PLAYER_ACTION_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PLAYER_ACTION_descriptor(), enum_t_value);
}
inline bool PLAYER_ACTION_Parse(
    const std::string& name, PLAYER_ACTION* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PLAYER_ACTION>(
    PLAYER_ACTION_descriptor(), name, value);
}
enum ITEM_CATEGORY : int {
  ITEM_CATEGORY_ARMORS = 1,
  ITEM_CATEGORY_AMULETS = 2,
  ITEM_CATEGORY_BOOTS = 3,
  ITEM_CATEGORY_CONTAINERS = 4,
  ITEM_CATEGORY_DECORATION = 5,
  ITEM_CATEGORY_FOOD = 6,
  ITEM_CATEGORY_HELMETS_HATS = 7,
  ITEM_CATEGORY_LEGS = 8,
  ITEM_CATEGORY_OTHERS = 9,
  ITEM_CATEGORY_POTIONS = 10,
  ITEM_CATEGORY_RINGS = 11,
  ITEM_CATEGORY_RUNES = 12,
  ITEM_CATEGORY_SHIELDS = 13,
  ITEM_CATEGORY_TOOLS = 14,
  ITEM_CATEGORY_VALUABLES = 15,
  ITEM_CATEGORY_AMMUNITION = 16,
  ITEM_CATEGORY_AXES = 17,
  ITEM_CATEGORY_CLUBS = 18,
  ITEM_CATEGORY_DISTANCE_WEAPONS = 19,
  ITEM_CATEGORY_SWORDS = 20,
  ITEM_CATEGORY_WANDS_RODS = 21,
  ITEM_CATEGORY_PREMIUM_SCROLLS = 22,
  ITEM_CATEGORY_TIBIA_COINS = 23,
  ITEM_CATEGORY_CREATURE_PRODUCTS = 24
};
bool ITEM_CATEGORY_IsValid(int value);
constexpr ITEM_CATEGORY ITEM_CATEGORY_MIN = ITEM_CATEGORY_ARMORS;
constexpr ITEM_CATEGORY ITEM_CATEGORY_MAX = ITEM_CATEGORY_CREATURE_PRODUCTS;
constexpr int ITEM_CATEGORY_ARRAYSIZE = ITEM_CATEGORY_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ITEM_CATEGORY_descriptor();
template<typename T>
inline const std::string& ITEM_CATEGORY_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ITEM_CATEGORY>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ITEM_CATEGORY_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ITEM_CATEGORY_descriptor(), enum_t_value);
}
inline bool ITEM_CATEGORY_Parse(
    const std::string& name, ITEM_CATEGORY* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ITEM_CATEGORY>(
    ITEM_CATEGORY_descriptor(), name, value);
}
enum PLAYER_PROFESSION : int {
  PLAYER_PROFESSION_ANY = -1,
  PLAYER_PROFESSION_NONE = 0,
  PLAYER_PROFESSION_KNIGHT = 1,
  PLAYER_PROFESSION_PALADIN = 2,
  PLAYER_PROFESSION_SORCERER = 3,
  PLAYER_PROFESSION_DRUID = 4,
  PLAYER_PROFESSION_PROMOTED = 10
};
bool PLAYER_PROFESSION_IsValid(int value);
constexpr PLAYER_PROFESSION PLAYER_PROFESSION_MIN = PLAYER_PROFESSION_ANY;
constexpr PLAYER_PROFESSION PLAYER_PROFESSION_MAX = PLAYER_PROFESSION_PROMOTED;
constexpr int PLAYER_PROFESSION_ARRAYSIZE = PLAYER_PROFESSION_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PLAYER_PROFESSION_descriptor();
template<typename T>
inline const std::string& PLAYER_PROFESSION_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PLAYER_PROFESSION>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PLAYER_PROFESSION_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PLAYER_PROFESSION_descriptor(), enum_t_value);
}
inline bool PLAYER_PROFESSION_Parse(
    const std::string& name, PLAYER_PROFESSION* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PLAYER_PROFESSION>(
    PLAYER_PROFESSION_descriptor(), name, value);
}
enum ANIMATION_LOOP_TYPE : int {
  ANIMATION_LOOP_TYPE_PINGPONG = -1,
  ANIMATION_LOOP_TYPE_INFINITE = 0,
  ANIMATION_LOOP_TYPE_COUNTED = 1
};
bool ANIMATION_LOOP_TYPE_IsValid(int value);
constexpr ANIMATION_LOOP_TYPE ANIMATION_LOOP_TYPE_MIN = ANIMATION_LOOP_TYPE_PINGPONG;
constexpr ANIMATION_LOOP_TYPE ANIMATION_LOOP_TYPE_MAX = ANIMATION_LOOP_TYPE_COUNTED;
constexpr int ANIMATION_LOOP_TYPE_ARRAYSIZE = ANIMATION_LOOP_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ANIMATION_LOOP_TYPE_descriptor();
template<typename T>
inline const std::string& ANIMATION_LOOP_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ANIMATION_LOOP_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ANIMATION_LOOP_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ANIMATION_LOOP_TYPE_descriptor(), enum_t_value);
}
inline bool ANIMATION_LOOP_TYPE_Parse(
    const std::string& name, ANIMATION_LOOP_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ANIMATION_LOOP_TYPE>(
    ANIMATION_LOOP_TYPE_descriptor(), name, value);
}
enum HOOK_TYPE : int {
  HOOK_TYPE_SOUTH = 1,
  HOOK_TYPE_EAST = 2
};
bool HOOK_TYPE_IsValid(int value);
constexpr HOOK_TYPE HOOK_TYPE_MIN = HOOK_TYPE_SOUTH;
constexpr HOOK_TYPE HOOK_TYPE_MAX = HOOK_TYPE_EAST;
constexpr int HOOK_TYPE_ARRAYSIZE = HOOK_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HOOK_TYPE_descriptor();
template<typename T>
inline const std::string& HOOK_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HOOK_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HOOK_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HOOK_TYPE_descriptor(), enum_t_value);
}
inline bool HOOK_TYPE_Parse(
    const std::string& name, HOOK_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HOOK_TYPE>(
    HOOK_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace shared
}  // namespace protobuf
}  // namespace tibia

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::tibia::protobuf::shared::PLAYER_ACTION> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tibia::protobuf::shared::PLAYER_ACTION>() {
  return ::tibia::protobuf::shared::PLAYER_ACTION_descriptor();
}
template <> struct is_proto_enum< ::tibia::protobuf::shared::ITEM_CATEGORY> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tibia::protobuf::shared::ITEM_CATEGORY>() {
  return ::tibia::protobuf::shared::ITEM_CATEGORY_descriptor();
}
template <> struct is_proto_enum< ::tibia::protobuf::shared::PLAYER_PROFESSION> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tibia::protobuf::shared::PLAYER_PROFESSION>() {
  return ::tibia::protobuf::shared::PLAYER_PROFESSION_descriptor();
}
template <> struct is_proto_enum< ::tibia::protobuf::shared::ANIMATION_LOOP_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tibia::protobuf::shared::ANIMATION_LOOP_TYPE>() {
  return ::tibia::protobuf::shared::ANIMATION_LOOP_TYPE_descriptor();
}
template <> struct is_proto_enum< ::tibia::protobuf::shared::HOOK_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tibia::protobuf::shared::HOOK_TYPE>() {
  return ::tibia::protobuf::shared::HOOK_TYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_shared_2eproto
